# Generated by Django 6.0.2 on 2026-02-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='recommendations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
