# Generated by Django 6.0.2 on 2026-02-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_document_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='improved_file',
            field=models.FileField(blank=True, null=True, upload_to='improved_contracts/'),
        ),
    ]
